module.exports = {
  vendorDirectFulfillmentShipping:{
    __versions:[
    	'v1'
  	],
    __operations:[
    	'getShippingLabels',
			'submitShippingLabelRequest',
			'getShippingLabel',
			'submitShipmentConfirmations',
			'submitShipmentStatusUpdates',
			'getCustomerInvoices',
			'getCustomerInvoice',
			'getPackingSlips',
			'getPackingSlip'
  	],
    ...require('./versions/vendor_direct_fulfillment_shipping/vendorDirectFulfillmentShipping_v1')
  }
};