// For a list of required and optional body, query or path parameters for resources please see official references:
// --> https://github.com/amzn/selling-partner-api-docs/tree/main/references

module.exports = {
  ...require("./resources/amazonWarehousingAndDistribution"),
  ...require("./resources/aplusContent"),
  ...require("./resources/applicationManagement"),
  ...require("./resources/catalogItems"),
  ...require("./resources/dataKiosk"),
  ...require("./resources/easyShip"),
  ...require("./resources/fbaInboundEligibility"),
  ...require("./resources/fbaInventory"),
  ...require("./resources/feeds"),
  ...require("./resources/finances"),
  ...require("./resources/fulfillmentInbound"),
  ...require("./resources/fulfillmentOutbound"),
  ...require("./resources/listingsItems"),
  ...require("./resources/listingsRestrictions"),
  ...require("./resources/merchantFulfillment"),
  ...require("./resources/messaging"),
  ...require("./resources/notifications"),
  ...require("./resources/orders"),
  ...require("./resources/productFees"),
  ...require("./resources/productPricing"),
  ...require("./resources/productTypeDefinitions"),
  ...require("./resources/replenishment"),
  ...require("./resources/reports"),
  ...require("./resources/sales"),
  ...require("./resources/sellers"),
  ...require("./resources/services"),
  ...require("./resources/shipmentInvoicing"),
  ...require("./resources/shipping"),
  ...require("./resources/solicitations"),
  ...require("./resources/supplySources"),
  ...require("./resources/tokens"),
  ...require("./resources/uploads"),
  ...require("./resources/vendorDirectFulfillmentInventory"),
  ...require("./resources/vendorDirectFulfillmentOrders"),
  ...require("./resources/vendorDirectFulfillmentPayments"),
  ...require("./resources/vendorDirectFulfillmentSandboxTestData"),
  ...require("./resources/vendorDirectFulfillmentShipping"),
  ...require("./resources/vendorDirectFulfillmentTransactions"),
  ...require("./resources/vendorInvoices"),
  ...require("./resources/vendorOrders"),
  ...require("./resources/vendorShipments"),
  ...require("./resources/vendorTransactionStatus")
};
